### ISSUE TITLE
Making it easier for people without coding expirience.

### ISSUE THREAD

**Issue by access3424** [AlexandrErohin/home-assistant-flightradar24#102]
Hi,

I am an airline pilot and I would like to display on my wife's dashboard where my aircraft is throughout the day. I can add my flight to the tracked flights but don't know how to display it on a map and also how to automate the removal of the tracked flight once it is complete. I am missing how to get the flight number variable  from the sensor and pass it onto the text.flightradar24_remove_from_track

**Comment by AlexandrErohin** [comment]
Hi
To show your flights you may use this
https://github.com/AlexandrErohin/home-assistant-flightradar24?tab=readme-ov-file#lovelace-card

To automate the removal you may use this
```
automation:
  - alias: "Track flights"
    trigger:
      platform: event
      event_type: flightradar24_tracked_landed
    action:
      - service: text.set_value
        data:
          value: "{{ trigger.event.data.aircraft_registration }}"
        target:
          entity_id: text.flightradar24_remove_from_track
```
