### ISSUE TITLE
FR24 Flight Entry Notification constantly being triggered.

### ISSUE THREAD

**Issue by peter-mc** [AlexandrErohin/home-assistant-flightradar24#116]
Not sure if this is by design, but it seems like a bug.

Since the integration update to v1.24.0 a "Flight Entry Notification" (sensor.flightradar24_current_in_area) automation is being constantly triggered (every 10-15 seconds), not just when a flight has entered the area, as it used to be.

Seems silly to be constantly triggering it when there are no flights in the area...

![Image](https://github.com/user-attachments/assets/e8b12d65-3f2d-4b0c-affd-e771ca5b75d4)

**Comment by AlexandrErohin** [comment]
@peter-mc What automation code do you use?

**Comment by peter-mc** [comment]
> [@peter-mc](https://github.com/peter-mc) What automation code do you use?

This is the code in the automation, the only thing that changed was updating to  v1.24.0. I actually have this on 2 different Home Assistants, and the behaviour was identical...

I watched it going from only trigerring when an aircraft was in the area, and updating to  v1.24.0 and immediately it started this continuous trigerring...



```
alias: FR24_2 Flight Entry Notification
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.flightradar24_current_in_area
conditions: []
actions:
  - action: script.fr24_3_get_current_flight_details
    data: {}
    response_variable: result
  - action: script.fr24_1_send_message_to_show10
    data:
      message: Flight {{ result.value }}
mode: single
```
