### ISSUE TITLE
Confused on Adding Track

### ISSUE THREAD

**Issue by magaman** [AlexandrErohin/home-assistant-flightradar24#34]
I just added the integration as we are near an airport and I wanted to figure out what are the various helicopters circling at times, without having to jump into the FlightRadar app. I have the helicopter callsigns saved that I wanted to track and then alert on when they are in the area. I assumed it was as simple as adding a track and then that would show me when any of the added tracks added are in the area, but that doesn't seem to be the case.

I'm trying to wrap my head around how I would then filter the list of in the area to only list or count this set of callsigns.

**Comment by AlexandrErohin** [comment]
Hi
You may use callsign filter in automation like
```
alias: Flight Radar Test
description: ""
trigger:
  - platform: event
    event_type: flightradar24_entry
condition:
  - condition: template
    value_template: "{{ trigger.event.data.callsign in ('RRR','BOE','AIB','NASA','000','ZZZ') }}"
action:
  - service: notify.samandsinead
    data:
      message: >-
        Special flight {{ trigger.event.data.callsign }} to {{  
        trigger.event.data.airport_destination_city }} altitude of {{
        trigger.event.data.altitude }} {{ trigger.event.aircraft_code }}
      data:
        actions:
          - action: URI
            title: Open Flight Radar
            uri: /mushroom-guide/flight-radar
mode: single
```
