### ISSUE TITLE
Aircrafts History

### ISSUE THREAD

**Issue by gavrilov** [AlexandrErohin/home-assistant-flightradar24#50]
Can I somehow display the history of the aircrafts that were in area (with Lovelace card)? For example, in the last hour?

Can I also display current and past aircrafts in my area in Grafana?

**Comment by AlexandrErohin** [comment]
Hi.
There is a flightradar24_entry event which you can use in automation to pass a new aircraft info to any analytics system you need or create sensors for your needs
P.S. Dont forget please to give a star to the repo :)

**Comment by jgverweij** [comment]
Customize to your needs:

```yaml
template:
  # Template Flightradar sensor

  - trigger:
      - platform: event
        event_type: flightradar24_exit

    sensor:
      - unique_id: flightradar24_last_flights
        name: "FlightRadar24 Last flights"
        state: >-
          {% set flight = trigger.event.data %}
          {{ flight.flight_number }} - {{ flight.airline_short }} - {{ flight.aircraft_model }} ({{ flight.aircraft_registration }})
          {{ flight.airport_origin_city }} > {{ flight.airport_destination_city }}
        attributes:
          flights: >-
            {% set n = 5 %}
            {% set m = this.attributes.flights | count | default(0) %}
            {{ [ trigger.event.data ] + 
               ( [] if m == 0 else 
                 this.attributes.flights[0:n-1] )
            }}
          icon: mdi:airplane
```

This is based on an event that occurs when an aircraft leaves the area. State is a bit different from the examples in the documentation, but you can modify it as you like. The sensor has the same structure as sensor.flighradar24_current_in_area and so you can use the same markdown code.

**Comment by AlexandrErohin** [comment]
@jgverweij Thank you! I have added it to README

**Comment by jgverweij** [comment]
@Koalamanx This message does appear in Visual Studio Code or in the logs?
You can replace the trigger part by this:
```yaml
  - trigger:
      - trigger: event
        event_type: flightradar24_exit
```

BTW, in my current setup I slightly changed the `flights` attribute to use `this.attributes.get()` with default value [], and added a timestamp `time_exit_area` for each flight:

```yaml
### Template
template:

  # Template Flightradar sensor
  - trigger:
      - trigger: event
        event_type: flightradar24_exit

    sensor:
      - unique_id: flightradar24_last_flights
        name: "FlightRadar24 Last flights"
        state: >-
          {% set flight = trigger.event.data %}
          {{ flight.flight_number }} - {{ flight.airline_short }} - {{ flight.aircraft_model }} ({{ flight.aircraft_registration }})
          {{ flight.airport_origin_city }} > {{ flight.airport_destination_city }}
        attributes:
          flights: >-
            {% set n = 5 %}
            {{ [ dict( trigger.event.data, time_exit_area=trigger.event.time_fired | as_timestamp | int ) ]
               + this.attributes.get('flights', [])[0:n-1] }}
          icon: mdi:airplane

```
