### ISSUE TITLE
Add a link and a question about callsign / flightnr

### ISSUE THREAD

**Issue by 1mfaasj** [AlexandrErohin/home-assistant-flightradar24#7]
Hi!
1. Because there are a lot of attributes (flight fields) it could be nice to add a link to it where you can click for more information about the flight or aircraft.

Is that possible to add into your integration?
For instance this url, I think if you search for the spotted flightnumber on this website, it gives you more information.

The main website: https://www.flightaware.com/
and an example of a flight: https://www.flightaware.com/live/flight/BEL8YE

Then you can setup an alerting like this:

```
service: notify.family
data:
  title: Flightradar
  message: Flightnumber {{ trigger.event.data.callsign }}
  data:
    actions:
      - action: URI
        title: More Info
        uri: >-
          https://www.flightaware.com/live/flight/{{
          trigger.event.data.??? }}
```

2. what is the purpose of the sensors? because they stay at "0" all the time?
![image](https://github.com/AlexandrErohin/home-assistant-flightradar24/assets/71582854/746eec4b-9570-4930-996e-b18d8063e01d)

only when I click on the exited sensor I see a count, but not at the entered sensor. thats strange right?
a flight should be enter AND exit in a certain zone.
![image](https://github.com/AlexandrErohin/home-assistant-flightradar24/assets/71582854/8d4cae63-c3ce-4703-9555-e3f8715fac46)
![image](https://github.com/AlexandrErohin/home-assistant-flightradar24/assets/71582854/5ecf9d32-2183-413d-876d-641e8990a0e0)

The attritribute flights should be filled with additional information about the flights right? but stays empty here.
What I would like to see is a list of past flights in the area in a lovelace card.

4. Oh and what is the difference between callsign and flight number? it looks the same

Thanks
