### ISSUE TITLE
Lovelace Card Bug

### ISSUE THREAD

**Issue by cataseven** [AlexandrErohin/home-assistant-flightradar24#71]
If any of flights under sensor.flightradar24_additional_tracked returns no data then lovelace card show nothing including the other tracked flights with enough info. 

Ex:

Add 4 flights. Lovelace card shows all. If 1 of the flights returns no info (not enough attributes) then also the other 3 flights is not shown on the card.

**Comment by AlexandrErohin** [comment]
@cataseven Hi
I have fixed the markdown. Please try it

**Comment by cataseven** [comment]
Thank you so mueh. Tested and done.

**Comment by AlexandrErohin** [comment]
@cataseven Yes, the markdown works for this also see this part
```
...
{% else%}
          <ha-icon icon="mdi:airplane"></ha-icon>{{ flight.flight_number }} - {{ flight.callsign }} - {{ flight.tracked_type }}
          {% endif%}{% endfor %}
```

**Comment by cataseven** [comment]
I wrote my own markdown card so I get the bug I think. However for a common solution I wrote this automation.

Maybe you can update your code as "If tracked_type goes from live to schdule then remove the flight from FlightRadar24 Additional tracked sensor"

```
alias: Action (Delete Flight Number)
description: ""
triggers:
  - event_type: state_changed
    trigger: event
conditions:
  - condition: template
    value_template: >-
      {{ trigger.event.data.new_state.domain == 'device_tracker' and
      trigger.event.data.new_state.attributes.tracked_type == 'schedule' and
      trigger.event.data.old_state.attributes.tracked_type == 'live'}}
actions:
  - action: text.set_value
    metadata: {}
    data:
      value: "{{ trigger.event.data.old_state.attributes.flight_number }}"
    target:
      entity_id: text.flightradar24_remove_from_track
```
