### ISSUE TITLE
Remove from Track using service calls

### ISSUE THREAD

**Issue by brownbloodspider** [AlexandrErohin/home-assistant-flightradar24#75]
I cant find a way to call a service and remove a flight from tracking. It seems I can only do this from UI. Most times I want to track a flight only. Once the flight lands I want to remove it from flight track as I see the add on keeps tracking the flight until I manually remove it.

I can write a quick NodeRed flow to remove the flight, but I cant find an Action (service call) to remove it. Any help will be appreciated.

**Comment by AlexandrErohin** [comment]
Hi.
There is an example in README how to add a flight for track - https://github.com/AlexandrErohin/home-assistant-flightradar24?tab=readme-ov-file#automation

You just need to replace text.flightradar24_add_to_track to text.flightradar24_remove_from_track

**Comment by AlexandrErohin** [comment]
@brownbloodspider Dont forget please to give a star to the repo :)

**Comment by cataseven** [comment]
> I cant find a way to call a service and remove a flight from tracking. It seems I can only do this from UI. Most times I want to track a flight only. Once the flight lands I want to remove it from flight track as I see the add on keeps tracking the flight until I manually remove it.
> 
> I can write a quick NodeRed flow to remove the flight, but I cant find an Action (service call) to remove it. Any help will be appreciated.

```
alias: Action (Delete Flight Number)
description: ""
triggers:
  - event_type: state_changed
    trigger: event
conditions:
  - condition: template
    value_template: >-
      {{ trigger.event.data.new_state.domain == 'device_tracker' and
      trigger.event.data.new_state.attributes.tracked_type == 'schedule' and
      trigger.event.data.old_state.attributes.tracked_type == 'live'}}
actions:
  - action: text.set_value
    metadata: {}
    data:
      value: "{{ trigger.event.data.old_state.attributes.flight_number }}"
    target:
      entity_id: text.flightradar24_remove_from_track
```
