### ISSUE TITLE
New problem with counting flights in my area

### ISSUE THREAD

**Issue by carveitup** [AlexandrErohin/home-assistant-flightradar24#81]
This is a great integration that I have been using for a while. My son is really into aircraft and commercial flight info and likes to monitor local activity.

I had it set up to keep track of the number of flights in my area over the past 24 hours just to get an idea of how busy the airspace is. To do this, I used a statistic helper that was set up like this in my configuration.yaml:

```
sensor:
  - platform: statistics
    name: "Flights in past 24 hours"
    entity_id: sensor.flightradar24_entered_area
    state_characteristic: count
    max_age:
      hours: 24
```
It was working fine until a few weeks ago when it suddenly started counting much more frequently, going from maybe 250 per day (5km radius) to 17,000+ per day. It seems like it is recording all flights instead of just flights within my radius. Is this a bug with the FlightRadar24 or perhaps something changed in home assistant related to the statistics platform?
