### ISSUE TITLE
YAML Syntax: "Message malformed Extra keys not allowed@data ["automation"]

### ISSUE THREAD

**Issue by jmlk52** [AlexandrErohin/home-assistant-flightradar24#91]
Copy paste the automation "Scheduled Flight takes off" and "Flight entry notification" at configuration yaml (as per description) or when entered after Create Automation (new empty Automation, in YAML code) results in syntax error **"Message malformed Extra keys not allowed@data ["automation"]**. Please note that I did not modify the YAML text in any way, except added the correct device (_ipad_johan) for notification. Despite the error result (syntax error YAML) the automation seems to work, I received a notification at my iPad. The text at **automations.yaml** looks as follows (and gives a green check mark at the top right):
- id: '1734403339412'
  alias: Flight entry notification a
  description: ''
  triggers:
  - event_type: flightradar24_entry
    trigger: event
  conditions: []
  actions:
  - data:
      message: Flight entry of {{ trigger.event.data.callsign }} to {{ trigger.event.data.airport_destination_city
        }} [Open FlightRadar](https://www.flightradar24.com/{{ trigger.event.data.callsign
        }})
      data:
        url: https://fr24.com/{{ trigger.event.data.callsign }}/{{ trigger.event.data.id
          }}
        image: '{{ trigger.event.data.aircraft_photo_medium }}'
    action: notify.mobile_app_ijohan
  mode: single.

Question:
How to prevent: "Message malformed Extra keys not allowed@data ["automation"] 
please note that  both attached pictures in this message are screen copy from Create Automation from scratch.

Yesterday I pasted the YAML automation straight into the configuration.yaml. Response: "Message malformed Extra keys not allowed@data ["automation"], ignored this with the result that all other automations stopped working. I restored the Back Up.

![flightradar24 error2](https://github.com/user-attachments/assets/0c8d4b82-bf4d-4df1-ba41-55d0af7e2769)
![flightradar24-error](https://github.com/user-attachments/assets/dc97d322-ac77-46ed-b3ab-939e3ab9ddcc)

**Comment by AlexandrErohin** [comment]
If you try to post automation via GUI - you dont need `automation` key and it would look like this
```
alias: "Flight entry notification"
trigger:
    platform: event
    event_type: flightradar24_entry
action:
    service: notify.mobile_app_<device_name>
    data:
        message: >-
        Flight entry of {{ trigger.event.data.callsign }} to {{ trigger.event.data.airport_destination_city }}
          [Open FlightRadar](https://www.flightradar24.com/{{ trigger.event.data.callsign }})
        data:
            url: >-
                https://fr24.com/{{ trigger.event.data.callsign }}/{{
                trigger.event.data.id }}
            image: "{{ trigger.event.data.aircraft_photo_medium }}"
```
