### ISSUE TITLE
How to remove the ground vehicles?

### ISSUE THREAD

**Issue by TheHuskyCrobats** [AlexandrErohin/home-assistant-flightradar24#95]
Any ideea on how can I remove the ground vehicles? I have a lot showing if I track in an airport area.

**Comment by AlexandrErohin** [comment]
@TheHuskyCrobats You may filter by altitude. Or ground vehicles aircraft_code is GRND or null

**Comment by jgverweij** [comment]
Try this:

```yaml
type: vertical-stack
title: Flightradar24
cards:
 -  type: entities
    entities:
      - entity: sensor.flightradar24_current_in_area
        name: In area
  - type: conditional
    conditions:
      - condition: numeric_state
        entity: sensor.flightradar24_current_in_area
        above: 0
    card:
        type: markdown
        content: >-
          {% set data = state_attr('sensor.flightradar24_current_in_area', 'flights') %}
          {% for flight in data %}{% if (flight.tracked_type | default('live')) == 'live' %}
          {% if flight.aircraft_code is defined and flight.aircraft_code != 'GRND' %}
          {{ flight.flight_number }} - {{ flight.airline_short }} - {{ flight.aircraft_model }}
          {{ flight.airport_origin_city }}{% if flight.airport_origin_city %} [{{ flight.airport_origin_country_name }}] {% endif %} -> {{ flight.airport_destination_city }}{% if flight.airport_destination_country_code %} [{{ flight.airport_destination_country_name }}] {% endif %}
          {% if flight.time_scheduled_departure %}Departure - {{ flight.time_scheduled_departure | timestamp_custom('%H:%M') }}; {% endif %}{% if flight.time_scheduled_arrival%}Arrival - {{ flight.time_scheduled_arrival | timestamp_custom('%H:%M') }}{% endif %}
          Altitude - {{ flight.altitude }} ft{% if flight.altitude > 0 %} ({{(flight.altitude * 0.3048)| round(0)}} m){% endif %}; Gr. speed - {{ flight.ground_speed }} kts{% if flight.ground_speed > 0 %} ({{(flight.ground_speed * 1.852)| round(0)}} km/h){% endif %}
          {% else%}
          {{ flight.flight_number }} - {{ flight.callsign }} - {{ flight.tracked_type }}
          {% endif %}{% endif %}{% endfor %}
```

Hope this works as I tried to correct the yaml syntax where needed.
